apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests.yaml

configMapGenerator:
  - name: aplecatpereca-www
    namespace: misc
    files:
      - www/index.html
      - www/main.js
      - www/style.css

generatorOptions:
  disableNameSuffixHash: true
