apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lifebuddies/
  - whoami/
  - a-plecat-pereca/
  - kube-prometheus-stack/
  - cloudflare-secret.yaml
  - cloudflare-daemon.yaml
